controller_joint_names: ['', 'right_shoulder_link', 'right_deloid_joint', 'right_forearm_joint', 'left_shoulder_joint', 'left_deltoid_joint', 'left_forearm_joint', 'left_wrist_joint', 'neck_joint', 'head_joint', ]
